"""edited users table and added services table

Revision ID: 0519555ec847
Revises: 
Create Date: 2020-04-24 19:33:30.096766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0519555ec847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=True),
    sa.Column('service_author', sa.String(length=120), nullable=True),
    sa.Column('service_page_call', sa.String(length=120), nullable=True),
    sa.Column('service_service_call', sa.String(length=120), nullable=True),
    sa.Column('service_api_endpoint', sa.String(length=120), nullable=True),
    sa.Column('service_tags', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_api_endpoint'),
    sa.UniqueConstraint('service_name'),
    sa.UniqueConstraint('service_page_call'),
    sa.UniqueConstraint('service_service_call')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('user_type', sa.String(length=30), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Services')
    # ### end Alembic commands ###
